function Controlfilter() {
    return $([
     '<div class="row">',
              '<div class="col-md-2 col-xs-12">',
                  '<label class="pull-right">ช่องทางเติมเงิน :</label>',
              '</div>',
              '<div class="col-md-4 col-xs-12">',
                   '<select id="topup_type" class="form-control">',
                       '<option value="2" >ทั้งหมด</option>',
                       '<option value="0" >เติมเงินผ่านโรงเรียน</option>',
                       '<option value="1" >เติมเงินผ่านมือถือ</option>',
                   '</select>',
              '</div>',
              '<div class="col-md-2 col-xs-12 topup_type" style="display: none;">',
                  '<label class="pull-right">ประเภทรายการ :</label>',
              '</div>',
              '<div class="col-md-4 col-xs-12 topup_type" style="display: none;">',
                   '<select id="ddlSearch" class="form-control">',
                       '<option value="0" >ทั้งหมด</option>',
                       '<option value="1" >ผู้เติมเงิน</option>',
                       '<option value="2" >ผู้รับเติมเงิน</option>',
                   '</select>',
              '</div>',
          '</div>',
          '<div class="row hidden type_row_0">',
              '<div class="col-md-2 col-xs-12">',
                  '<label class="pull-right">ประเภทผู้เติม :</label>',
              '</div>',
              '<div class="col-md-4 col-xs-12">',
                  '<select name="selecttype" id="selecttype" class="form-control">',
                      '<option value="2" >ทั้งหมด</option>',
                      '<option value="0">นักเรียน</option>',
                      '<option value="1">พนักงาน</option>',
                  '</select>',
              '</div>',
              '<div class="col-xs-6">',
              '</div>',
          '</div>',
          '<div class="row hidden type_row_1">',
              '<div class="col-md-2 col-xs-12">',
                  '<label class="pull-right">ระดับชั้นเรียน :<span style="color: red;"></span></label>',
              '</div>',
              '<div class="col-md-4 col-xs-12">',
                  '<select name="selectlevel" id="selectlevel" class="form-control dropdown">',
                  '</select>',
              '</div>',
              '<div class="col-md-2 col-xs-12">',
                  '<label class="pull-right">ชั้นเรียน :<span style="color: red;"></span></label>',
              '</div>',
              '<div class="col-md-4 col-xs-12">',
                  '<select name="selectsublevel" id="selectsublevel" class="form-control">',
                  '</select>',
             '</div>',
          '</div>',
          '<div class="row hidden type_row_2">',
              '<div class="col-md-2 col-xs-12">',
                  '<label class="pull-right">ชื่อ - นามสกุล :<span style="color: red;"></span></label>',
              '</div>',
              '<div class="col-md-4 col-xs-12">',
                    '<input type="text" name="sname" class="form-control col-xs-12 col-md-12" />',
                    '<input type="hidden" name="iduser" class="form-control" />',
                 //'<div class="input-group">',
                    //'<div class="input-group-addon">',
                    //      '<i class="glyphicon glyphicon-remove"></i>',
                    //'</div>',
                //'</div>',
              '</div>',
              '<div class="col-xs-6">',
              '</div>',
          '</div>',
          '<div class="row row--space hidden" id="sname">',
              '<div class="col-md-2 col-xs-12">',
                  '<label class="pull-right">ชื่อ-นามสกุล :</label>',
              '</div>',
              '<div class="col-md-8 col-xs-12">',
              '</div>',
          '</div>',
          '<div class="row row--space">',
              '<div class="col-md-2 col-xs-12">',
                  '<label class="pull-right">วันที่ :</label>',
              '</div>',
              '<div class="col-md-4 col-xs-12">',
                   '<input type="text" id="txtdStart"  class="form-control datepicker"/>',
              '</div>',
              '<div class="col-md-2 col-xs-12">',
                  '<label class="pull-right">ถึง :</label>',
              '</div>',
              '<div class="col-md-4 col-xs-12">',
                   '<input type="text" id="txtdEnd" class="form-control datepicker"/>',
              '</div>',
          '</div>'
    ].join("\n"));
}
