namespace FingerprintPayment.ViewModels
{
    public class studentlist2
    {
        public int? sID { get; set; }
        public string sName { get; set; }
        public string note { get; set; }
        public bool toggleOn { get; set; }
        public string txtg1 { get; set; }
        public string txtg2 { get; set; }
        public string txtg3 { get; set; }
        public string txtg4 { get; set; }
        public string txtg5 { get; set; }
        public string txtg6 { get; set; }
        public string txtg7 { get; set; }
        public string txtg8 { get; set; }
        public string txtg9 { get; set; }
        public string txtg10 { get; set; }
        public string txtg11 { get; set; }
        public string txtg12 { get; set; }
        public string txtg13 { get; set; }
        public string txtg14 { get; set; }
        public string txtg15 { get; set; }
        public string txtg16 { get; set; }
        public string txtg17 { get; set; }
        public string txtg18 { get; set; }
        public string txtg19 { get; set; }
        public string txtg20 { get; set; }
        public string txtgmid { get; set; }
        public string txtglate { get; set; }
        public string number { get; set; }
        public string txtGoodBehavior { get; set; }
        public string txtGoodReading { get; set; }
        public string txtSamattana { get; set; }
        public string txtSpecial { get; set; }
        public string txtb1 { get; set; }
        public string txtb2 { get; set; }
        public string txtb3 { get; set; }
        public string txtb4 { get; set; }
        public string txtb5 { get; set; }
        public string txtb6 { get; set; }
        public string txtb7 { get; set; }
        public string txtb8 { get; set; }
        public string txtb9 { get; set; }
        public string txtb10 { get; set; }
        public string txtchewut1 { get; set; }
        public string txtchewut2 { get; set; }
        public string txtchewut3 { get; set; }
        public string txtchewut4 { get; set; }
        public string txtchewut5 { get; set; }
        public string txtchewut6 { get; set; }
        public string txtchewut7 { get; set; }
        public string txtchewut8 { get; set; }
        public string txtchewut9 { get; set; }
        public string txtchewut10 { get; set; }
        public string txtchewut11 { get; set; }
        public string txtchewut12 { get; set; }
        public string txtchewut13 { get; set; }
        public string txtchewut14 { get; set; }
        public string txtchewut15 { get; set; }
        public string txtchewut16 { get; set; }
        public string txtchewut17 { get; set; }
        public string txtchewut18 { get; set; }
        public string txtchewut19 { get; set; }
        public string txtchewut20 { get; set; }
        public int? sort2 { get; set; }
        public int sort1int { get; set; }
        public string sort1txt { get; set; }
        public string getgrade { get; set; }
        public string totalquiz { get; set; }
        public string total100 { get; set; }
        public string totalfinal { get; set; }
        public string totalmid { get; set; }
        public string studentid { get; set; }
        public string gradeprint { get; set; }
        public string get70 { get; set; }
        public string classroom { get; set; }
    }
}