using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using JabjaiEntity.DB;
using MasterEntity;
using FingerprintPayment.Class;
using JabjaiMainClass;
using System.Globalization;
using System.Web.DynamicData;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.IO;
using JabjaiSchoolGradeEntity;

namespace FingerprintPayment.grade
{
    public partial class SchoolReportPrint : System.Web.UI.Page
    {
        private JWTToken.userData userData = new JWTToken.userData();
        public static string GetPermission()
        {
            return (String)HttpContext.Current.Session["sEntities"];
        }
        protected void Page_Load(object sender, EventArgs e)
        {
            JWTToken token = new JWTToken();
            if (token.CheckToken(HttpContext.Current)) { userData = token.getTokenValues(HttpContext.Current); }

            if (Session["sEntities"] == null) Response.Redirect("~/Default.aspx");

            if (string.IsNullOrEmpty(Session["sEmpID"] + "")) Response.Redirect("/Default.aspx");
            JabJaiEntities _db = new JabJaiEntities(Connection.StringConnectionSchool(HttpContext.Current.Session["sEntities"].ToString()));

            JabJaiMasterEntities _dbMaster = Connection.MasterEntities();



            string sEntities = HttpContext.Current.Session["sEntities"].ToString();
            var nCompany = _dbMaster.TCompanies.Where(w => w.sEntities == sEntities).FirstOrDefault();
            var schooldata = _dbMaster.TCompanies.Where(w => w.nCompany == nCompany.nCompany).FirstOrDefault();

            string idlv = Request.QueryString["idlv"];
            int? idlvn = Int32.Parse(idlv);
            string idlv2 = Request.QueryString["idlv2"];
            int? idlv2n = Int32.Parse(idlv2);
            var room = _db.TSubLevels.Where(w => w.nTSubLevel == idlvn && w.SchoolID == userData.CompanyID).FirstOrDefault();

            var room2 = _db.TTermSubLevel2.Where(w => w.nTermSubLevel2 == idlv2n && w.SchoolID == userData.CompanyID).FirstOrDefault();

            string addressnum = schooldata.sHomeNumber;
            string soy = " ซ." + schooldata.sSoy;
            string road = " ถ." + schooldata.sRoad;          
            string aumper = " " + schooldata.sAumpher;
            string province = " " + schooldata.sProvince;
            string post = " " + schooldata.sPost;            
            string phone = "โทร. " + schooldata.sPhoneOne;            
            
            if (schooldata.sRoad == "")
                road = "";
            if (schooldata.sSoy == "")
                soy = "";
            if (schooldata.sPhoneTwo != "" && schooldata.sPhoneTwo != null)
                phone = "โทร. "+schooldata.sPhoneOne + ", " + schooldata.sPhoneTwo;
            
            p1header1.Text = schooldata.sCompany;
            p1header2.Text = addressnum + soy + road  + aumper + province + post;
            p1header3.Text = phone;
            p2header1.Text = schooldata.sCompany;
            p2header2.Text = addressnum + soy + road + aumper + province + post;
            p2header3.Text = phone;
            p3header1.Text = schooldata.sCompany;
            p3header2.Text = addressnum + soy + road + aumper + province + post;
            p3header3.Text = phone;
            p4header1.Text = schooldata.sCompany;
            p4header2.Text = addressnum + soy + road + aumper + province + post;
            p4header3.Text = phone;
            p5header1.Text = schooldata.sCompany;
            p5header2.Text = addressnum + soy + road + aumper + province + post;
            p5header3.Text = phone;
            p6header1.Text = schooldata.sCompany;
            p6header2.Text = addressnum + soy + road + aumper + province + post;
            p6header3.Text = phone;
            p7header1.Text = schooldata.sCompany;
            p7header2.Text = addressnum + soy + road + aumper + province + post;
            p7header3.Text = phone;
            p8header1.Text = schooldata.sCompany;
            p8header2.Text = addressnum + soy + road + aumper + province + post;
            p8header3.Text = phone;
            p9header1.Text = schooldata.sCompany;
            p9header2.Text = addressnum + soy + road + aumper + province + post;
            p9header3.Text = phone;
            p10header1.Text = schooldata.sCompany;
            p10header2.Text = addressnum + soy + road + aumper + province + post;
            p10header3.Text = phone;
            p11header1.Text = schooldata.sCompany;
            p11header2.Text = addressnum + soy + road + aumper + province + post;
            p11header3.Text = phone;
            p12header1.Text = schooldata.sCompany;
            p12header2.Text = addressnum + soy + road + aumper + province + post;
            p12header3.Text = phone;
            p13header1.Text = schooldata.sCompany;
            p13header2.Text = addressnum + soy + road + aumper + province + post;
            p13header3.Text = phone;
            p14header1.Text = schooldata.sCompany;
            p14header2.Text = addressnum + soy + road + aumper + province + post;
            p14header3.Text = phone;
            p15header1.Text = schooldata.sCompany;
            p15header2.Text = addressnum + soy + road + aumper + province + post;
            p15header3.Text = phone;
            p16header1.Text = schooldata.sCompany;
            p16header2.Text = addressnum + soy + road + aumper + province + post;
            p16header3.Text = phone;
            p17header1.Text = schooldata.sCompany;
            p17header2.Text = addressnum + soy + road + aumper + province + post;
            p17header3.Text = phone;
            p18header1.Text = schooldata.sCompany;
            p18header2.Text = addressnum + soy + road + aumper + province + post;
            p18header3.Text = phone;
            p19header1.Text = schooldata.sCompany;
            p19header2.Text = addressnum + soy + road + aumper + province + post;
            p19header3.Text = phone;
            p20header1.Text = schooldata.sCompany;
            p20header2.Text = addressnum + soy + road + aumper + province + post;
            p20header3.Text = phone;
            p21header1.Text = schooldata.sCompany;
            p21header2.Text = addressnum + soy + road + aumper + province + post;
            p21header3.Text = phone;
            p22header1.Text = schooldata.sCompany;
            p22header2.Text = addressnum + soy + road + aumper + province + post;
            p22header3.Text = phone;
            p23header1.Text = schooldata.sCompany;
            p23header2.Text = addressnum + soy + road + aumper + province + post;
            p23header3.Text = phone;
            p24header1.Text = schooldata.sCompany;
            p24header2.Text = addressnum + soy + road + aumper + province + post;
            p24header3.Text = phone;
            p25header1.Text = schooldata.sCompany;
            p25header2.Text = addressnum + soy + road + aumper + province + post;
            p25header3.Text = phone;
            p26header1.Text = schooldata.sCompany;
            p26header2.Text = addressnum + soy + road + aumper + province + post;
            p26header3.Text = phone;
            p27header1.Text = schooldata.sCompany;
            p27header2.Text = addressnum + soy + road + aumper + province + post;
            p27header3.Text = phone;
            p28header1.Text = schooldata.sCompany;
            p28header2.Text = addressnum + soy + road + aumper + province + post;
            p28header3.Text = phone;
            p29header1.Text = schooldata.sCompany;
            p29header2.Text = addressnum + soy + road + aumper + province + post;
            p29header3.Text = phone;
            p30header1.Text = schooldata.sCompany;
            p30header2.Text = addressnum + soy + road + aumper + province + post;
            p30header3.Text = phone;
            p31header1.Text = schooldata.sCompany;
            p31header2.Text = addressnum + soy + road + aumper + province + post;
            p31header3.Text = phone;
            p32header1.Text = schooldata.sCompany;
            p32header2.Text = addressnum + soy + road + aumper + province + post;
            p32header3.Text = phone;
            p33header1.Text = schooldata.sCompany;
            p33header2.Text = addressnum + soy + road + aumper + province + post;
            p33header3.Text = phone;
            p34header1.Text = schooldata.sCompany;
            p34header2.Text = addressnum + soy + road + aumper + province + post;
            p34header3.Text = phone;
            p35header1.Text = schooldata.sCompany;
            p35header2.Text = addressnum + soy + road + aumper + province + post;
            p35header3.Text = phone;
            p36header1.Text = schooldata.sCompany;
            p36header2.Text = addressnum + soy + road + aumper + province + post;
            p36header3.Text = phone;
            p37header1.Text = schooldata.sCompany;
            p37header2.Text = addressnum + soy + road + aumper + province + post;
            p37header3.Text = phone;
            p38header1.Text = schooldata.sCompany;
            p38header2.Text = addressnum + soy + road + aumper + province + post;
            p38header3.Text = phone;
            p39header1.Text = schooldata.sCompany;
            p39header2.Text = addressnum + soy + road + aumper + province + post;
            p39header3.Text = phone;
            p40header1.Text = schooldata.sCompany;
            p40header2.Text = addressnum + soy + road + aumper + province + post;
            p40header3.Text = phone;
            p41header1.Text = schooldata.sCompany;
            p41header2.Text = addressnum + soy + road + aumper + province + post;
            p41header3.Text = phone;
            p42header1.Text = schooldata.sCompany;
            p42header2.Text = addressnum + soy + road + aumper + province + post;
            p42header3.Text = phone;
            p43header1.Text = schooldata.sCompany;
            p43header2.Text = addressnum + soy + road + aumper + province + post;
            p43header3.Text = phone;
            p44header1.Text = schooldata.sCompany;
            p44header2.Text = addressnum + soy + road + aumper + province + post;
            p44header3.Text = phone;
            p45header1.Text = schooldata.sCompany;
            p45header2.Text = addressnum + soy + road + aumper + province + post;
            p45header3.Text = phone;
            p46header1.Text = schooldata.sCompany;
            p46header2.Text = addressnum + soy + road + aumper + province + post;
            p46header3.Text = phone;
            p47header1.Text = schooldata.sCompany;
            p47header2.Text = addressnum + soy + road + aumper + province + post;
            p47header3.Text = phone;
            p48header1.Text = schooldata.sCompany;
            p48header2.Text = addressnum + soy + road + aumper + province + post;
            p48header3.Text = phone;
            p49header1.Text = schooldata.sCompany;
            p49header2.Text = addressnum + soy + road + aumper + province + post;
            p49header3.Text = phone;
            p50header1.Text = schooldata.sCompany;
            p50header2.Text = addressnum + soy + road + aumper + province + post;
            p50header3.Text = phone;
            p51header1.Text = schooldata.sCompany;
            p51header2.Text = addressnum + soy + road + aumper + province + post;
            p51header3.Text = phone;
            p52header1.Text = schooldata.sCompany;
            p52header2.Text = addressnum + soy + road + aumper + province + post;
            p52header3.Text = phone;
            p53header1.Text = schooldata.sCompany;
            p53header2.Text = addressnum + soy + road + aumper + province + post;
            p53header3.Text = phone;
            p54header1.Text = schooldata.sCompany;
            p54header2.Text = addressnum + soy + road + aumper + province + post;
            p54header3.Text = phone;
            p55header1.Text = schooldata.sCompany;
            p55header2.Text = addressnum + soy + road + aumper + province + post;
            p55header3.Text = phone;
            p56header1.Text = schooldata.sCompany;
            p56header2.Text = addressnum + soy + road + aumper + province + post;
            p56header3.Text = phone;
            p57header1.Text = schooldata.sCompany;
            p57header2.Text = addressnum + soy + road + aumper + province + post;
            p57header3.Text = phone;
            p58header1.Text = schooldata.sCompany;
            p58header2.Text = addressnum + soy + road + aumper + province + post;
            p58header3.Text = phone;
            p59header1.Text = schooldata.sCompany;
            p59header2.Text = addressnum + soy + road + aumper + province + post;
            p59header3.Text = phone;
            p60header1.Text = schooldata.sCompany;
            p60header2.Text = addressnum + soy + road + aumper + province + post;
            p60header3.Text = phone;
            p61header1.Text = schooldata.sCompany;
            p61header2.Text = addressnum + soy + road + aumper + province + post;
            p61header3.Text = phone;
            p62header1.Text = schooldata.sCompany;
            p62header2.Text = addressnum + soy + road + aumper + province + post;
            p62header3.Text = phone;
            p63header1.Text = schooldata.sCompany;
            p63header2.Text = addressnum + soy + road + aumper + province + post;
            p63header3.Text = phone;
            p64header1.Text = schooldata.sCompany;
            p64header2.Text = addressnum + soy + road + aumper + province + post;
            p64header3.Text = phone;
            p65header1.Text = schooldata.sCompany;
            p65header2.Text = addressnum + soy + road + aumper + province + post;
            p65header3.Text = phone;
            p66header1.Text = schooldata.sCompany;
            p66header2.Text = addressnum + soy + road + aumper + province + post;
            p66header3.Text = phone;
            p67header1.Text = schooldata.sCompany;
            p67header2.Text = addressnum + soy + road + aumper + province + post;
            p67header3.Text = phone;
            p68header1.Text = schooldata.sCompany;
            p68header2.Text = addressnum + soy + road + aumper + province + post;
            p68header3.Text = phone;
            p69header1.Text = schooldata.sCompany;
            p69header2.Text = addressnum + soy + road + aumper + province + post;
            p69header3.Text = phone;
            p70header1.Text = schooldata.sCompany;
            p70header2.Text = addressnum + soy + road + aumper + province + post;
            p70header3.Text = phone;
            p71header1.Text = schooldata.sCompany;
            p71header2.Text = addressnum + soy + road + aumper + province + post;
            p71header3.Text = phone;
            p72header1.Text = schooldata.sCompany;
            p72header2.Text = addressnum + soy + road + aumper + province + post;
            p72header3.Text = phone;
            p73header1.Text = schooldata.sCompany;
            p73header2.Text = addressnum + soy + road + aumper + province + post;
            p73header3.Text = phone;
            p74header1.Text = schooldata.sCompany;
            p74header2.Text = addressnum + soy + road + aumper + province + post;
            p74header3.Text = phone;
            p75header1.Text = schooldata.sCompany;
            p75header2.Text = addressnum + soy + road + aumper + province + post;
            p75header3.Text = phone;
            p76header1.Text = schooldata.sCompany;
            p76header2.Text = addressnum + soy + road + aumper + province + post;
            p76header3.Text = phone;
            p77header1.Text = schooldata.sCompany;
            p77header2.Text = addressnum + soy + road + aumper + province + post;
            p77header3.Text = phone;
            p78header1.Text = schooldata.sCompany;
            p78header2.Text = addressnum + soy + road + aumper + province + post;
            p78header3.Text = phone;
            p79header1.Text = schooldata.sCompany;
            p79header2.Text = addressnum + soy + road + aumper + province + post;
            p79header3.Text = phone;
            p80header1.Text = schooldata.sCompany;
            p80header2.Text = addressnum + soy + road + aumper + province + post;
            p80header3.Text = phone;
            p81header1.Text = schooldata.sCompany;
            p81header2.Text = addressnum + soy + road + aumper + province + post;
            p81header3.Text = phone;
            p82header1.Text = schooldata.sCompany;
            p82header2.Text = addressnum + soy + road + aumper + province + post;
            p82header3.Text = phone;
            p83header1.Text = schooldata.sCompany;
            p83header2.Text = addressnum + soy + road + aumper + province + post;
            p83header3.Text = phone;
            p84header1.Text = schooldata.sCompany;
            p84header2.Text = addressnum + soy + road + aumper + province + post;
            p84header3.Text = phone;
            p85header1.Text = schooldata.sCompany;
            p85header2.Text = addressnum + soy + road + aumper + province + post;
            p85header3.Text = phone;
            p86header1.Text = schooldata.sCompany;
            p86header2.Text = addressnum + soy + road + aumper + province + post;
            p86header3.Text = phone;
            p87header1.Text = schooldata.sCompany;
            p87header2.Text = addressnum + soy + road + aumper + province + post;
            p87header3.Text = phone;
            p88header1.Text = schooldata.sCompany;
            p88header2.Text = addressnum + soy + road + aumper + province + post;
            p88header3.Text = phone;
            p89header1.Text = schooldata.sCompany;
            p89header2.Text = addressnum + soy + road + aumper + province + post;
            p89header3.Text = phone;
            p90header1.Text = schooldata.sCompany;
            p90header2.Text = addressnum + soy + road + aumper + province + post;
            p90header3.Text = phone;

            b2p1header1.Text = schooldata.sCompany;
            b2p1header2.Text = addressnum + soy + road + aumper + province + post;
            b2p1header3.Text = phone;
            b2p2header1.Text = schooldata.sCompany;
            b2p2header2.Text = addressnum + soy + road + aumper + province + post;
            b2p2header3.Text = phone;
            b2p3header1.Text = schooldata.sCompany;
            b2p3header2.Text = addressnum + soy + road + aumper + province + post;
            b2p3header3.Text = phone;
            b2p4header1.Text = schooldata.sCompany;
            b2p4header2.Text = addressnum + soy + road + aumper + province + post;
            b2p4header3.Text = phone;
            b2p5header1.Text = schooldata.sCompany;
            b2p5header2.Text = addressnum + soy + road + aumper + province + post;
            b2p5header3.Text = phone;
            b2p6header1.Text = schooldata.sCompany;
            b2p6header2.Text = addressnum + soy + road + aumper + province + post;
            b2p6header3.Text = phone;
            b2p7header1.Text = schooldata.sCompany;
            b2p7header2.Text = addressnum + soy + road + aumper + province + post;
            b2p7header3.Text = phone;
            b2p8header1.Text = schooldata.sCompany;
            b2p8header2.Text = addressnum + soy + road + aumper + province + post;
            b2p8header3.Text = phone;
            b2p9header1.Text = schooldata.sCompany;
            b2p9header2.Text = addressnum + soy + road + aumper + province + post;
            b2p9header3.Text = phone;
            b2p10header1.Text = schooldata.sCompany;
            b2p10header2.Text = addressnum + soy + road + aumper + province + post;
            b2p10header3.Text = phone;
            b2p11header1.Text = schooldata.sCompany;
            b2p11header2.Text = addressnum + soy + road + aumper + province + post;
            b2p11header3.Text = phone;
            b2p12header1.Text = schooldata.sCompany;
            b2p12header2.Text = addressnum + soy + road + aumper + province + post;
            b2p12header3.Text = phone;
            b2p13header1.Text = schooldata.sCompany;
            b2p13header2.Text = addressnum + soy + road + aumper + province + post;
            b2p13header3.Text = phone;
            b2p14header1.Text = schooldata.sCompany;
            b2p14header2.Text = addressnum + soy + road + aumper + province + post;
            b2p14header3.Text = phone;
            b2p15header1.Text = schooldata.sCompany;
            b2p15header2.Text = addressnum + soy + road + aumper + province + post;
            b2p15header3.Text = phone;
            b2p16header1.Text = schooldata.sCompany;
            b2p16header2.Text = addressnum + soy + road + aumper + province + post;
            b2p16header3.Text = phone;
            b2p17header1.Text = schooldata.sCompany;
            b2p17header2.Text = addressnum + soy + road + aumper + province + post;
            b2p17header3.Text = phone;
            b2p18header1.Text = schooldata.sCompany;
            b2p18header2.Text = addressnum + soy + road + aumper + province + post;
            b2p18header3.Text = phone;
            b2p19header1.Text = schooldata.sCompany;
            b2p19header2.Text = addressnum + soy + road + aumper + province + post;
            b2p19header3.Text = phone;
            b2p20header1.Text = schooldata.sCompany;
            b2p20header2.Text = addressnum + soy + road + aumper + province + post;
            b2p20header3.Text = phone;
            b2p21header1.Text = schooldata.sCompany;
            b2p21header2.Text = addressnum + soy + road + aumper + province + post;
            b2p21header3.Text = phone;
            b2p22header1.Text = schooldata.sCompany;
            b2p22header2.Text = addressnum + soy + road + aumper + province + post;
            b2p22header3.Text = phone;
            b2p23header1.Text = schooldata.sCompany;
            b2p23header2.Text = addressnum + soy + road + aumper + province + post;
            b2p23header3.Text = phone;
            b2p24header1.Text = schooldata.sCompany;
            b2p24header2.Text = addressnum + soy + road + aumper + province + post;
            b2p24header3.Text = phone;
            b2p25header1.Text = schooldata.sCompany;
            b2p25header2.Text = addressnum + soy + road + aumper + province + post;
            b2p25header3.Text = phone;
            b2p26header1.Text = schooldata.sCompany;
            b2p26header2.Text = addressnum + soy + road + aumper + province + post;
            b2p26header3.Text = phone;
            b2p27header1.Text = schooldata.sCompany;
            b2p27header2.Text = addressnum + soy + road + aumper + province + post;
            b2p27header3.Text = phone;
            b2p28header1.Text = schooldata.sCompany;
            b2p28header2.Text = addressnum + soy + road + aumper + province + post;
            b2p28header3.Text = phone;
            b2p29header1.Text = schooldata.sCompany;
            b2p29header2.Text = addressnum + soy + road + aumper + province + post;
            b2p29header3.Text = phone;
            b2p30header1.Text = schooldata.sCompany;
            b2p30header2.Text = addressnum + soy + road + aumper + province + post;
            b2p30header3.Text = phone;
            b2p31header1.Text = schooldata.sCompany;
            b2p31header2.Text = addressnum + soy + road + aumper + province + post;
            b2p31header3.Text = phone;
            b2p32header1.Text = schooldata.sCompany;
            b2p32header2.Text = addressnum + soy + road + aumper + province + post;
            b2p32header3.Text = phone;
            b2p33header1.Text = schooldata.sCompany;
            b2p33header2.Text = addressnum + soy + road + aumper + province + post;
            b2p33header3.Text = phone;
            b2p34header1.Text = schooldata.sCompany;
            b2p34header2.Text = addressnum + soy + road + aumper + province + post;
            b2p34header3.Text = phone;
            b2p35header1.Text = schooldata.sCompany;
            b2p35header2.Text = addressnum + soy + road + aumper + province + post;
            b2p35header3.Text = phone;
            b2p36header1.Text = schooldata.sCompany;
            b2p36header2.Text = addressnum + soy + road + aumper + province + post;
            b2p36header3.Text = phone;
            b2p37header1.Text = schooldata.sCompany;
            b2p37header2.Text = addressnum + soy + road + aumper + province + post;
            b2p37header3.Text = phone;
            b2p38header1.Text = schooldata.sCompany;
            b2p38header2.Text = addressnum + soy + road + aumper + province + post;
            b2p38header3.Text = phone;
            b2p39header1.Text = schooldata.sCompany;
            b2p39header2.Text = addressnum + soy + road + aumper + province + post;
            b2p39header3.Text = phone;
            b2p40header1.Text = schooldata.sCompany;
            b2p40header2.Text = addressnum + soy + road + aumper + province + post;
            b2p40header3.Text = phone;
            b2p41header1.Text = schooldata.sCompany;
            b2p41header2.Text = addressnum + soy + road + aumper + province + post;
            b2p41header3.Text = phone;
            b2p42header1.Text = schooldata.sCompany;
            b2p42header2.Text = addressnum + soy + road + aumper + province + post;
            b2p42header3.Text = phone;
            b2p43header1.Text = schooldata.sCompany;
            b2p43header2.Text = addressnum + soy + road + aumper + province + post;
            b2p43header3.Text = phone;
            b2p44header1.Text = schooldata.sCompany;
            b2p44header2.Text = addressnum + soy + road + aumper + province + post;
            b2p44header3.Text = phone;
            b2p45header1.Text = schooldata.sCompany;
            b2p45header2.Text = addressnum + soy + road + aumper + province + post;
            b2p45header3.Text = phone;
            b2p46header1.Text = schooldata.sCompany;
            b2p46header2.Text = addressnum + soy + road + aumper + province + post;
            b2p46header3.Text = phone;
            b2p47header1.Text = schooldata.sCompany;
            b2p47header2.Text = addressnum + soy + road + aumper + province + post;
            b2p47header3.Text = phone;
            b2p48header1.Text = schooldata.sCompany;
            b2p48header2.Text = addressnum + soy + road + aumper + province + post;
            b2p48header3.Text = phone;
            b2p49header1.Text = schooldata.sCompany;
            b2p49header2.Text = addressnum + soy + road + aumper + province + post;
            b2p49header3.Text = phone;
            b2p50header1.Text = schooldata.sCompany;
            b2p50header2.Text = addressnum + soy + road + aumper + province + post;
            b2p50header3.Text = phone;
            b2p51header1.Text = schooldata.sCompany;
            b2p51header2.Text = addressnum + soy + road + aumper + province + post;
            b2p51header3.Text = phone;
            b2p52header1.Text = schooldata.sCompany;
            b2p52header2.Text = addressnum + soy + road + aumper + province + post;
            b2p52header3.Text = phone;
            b2p53header1.Text = schooldata.sCompany;
            b2p53header2.Text = addressnum + soy + road + aumper + province + post;
            b2p53header3.Text = phone;
            b2p54header1.Text = schooldata.sCompany;
            b2p54header2.Text = addressnum + soy + road + aumper + province + post;
            b2p54header3.Text = phone;
            b2p55header1.Text = schooldata.sCompany;
            b2p55header2.Text = addressnum + soy + road + aumper + province + post;
            b2p55header3.Text = phone;
            b2p56header1.Text = schooldata.sCompany;
            b2p56header2.Text = addressnum + soy + road + aumper + province + post;
            b2p56header3.Text = phone;
            b2p57header1.Text = schooldata.sCompany;
            b2p57header2.Text = addressnum + soy + road + aumper + province + post;
            b2p57header3.Text = phone;
            b2p58header1.Text = schooldata.sCompany;
            b2p58header2.Text = addressnum + soy + road + aumper + province + post;
            b2p58header3.Text = phone;
            b2p59header1.Text = schooldata.sCompany;
            b2p59header2.Text = addressnum + soy + road + aumper + province + post;
            b2p59header3.Text = phone;
            b2p60header1.Text = schooldata.sCompany;
            b2p60header2.Text = addressnum + soy + road + aumper + province + post;
            b2p60header3.Text = phone;
            b2p61header1.Text = schooldata.sCompany;
            b2p61header2.Text = addressnum + soy + road + aumper + province + post;
            b2p61header3.Text = phone;
            b2p62header1.Text = schooldata.sCompany;
            b2p62header2.Text = addressnum + soy + road + aumper + province + post;
            b2p62header3.Text = phone;
            b2p63header1.Text = schooldata.sCompany;
            b2p63header2.Text = addressnum + soy + road + aumper + province + post;
            b2p63header3.Text = phone;
            b2p64header1.Text = schooldata.sCompany;
            b2p64header2.Text = addressnum + soy + road + aumper + province + post;
            b2p64header3.Text = phone;
            b2p65header1.Text = schooldata.sCompany;
            b2p65header2.Text = addressnum + soy + road + aumper + province + post;
            b2p65header3.Text = phone;
            b2p66header1.Text = schooldata.sCompany;
            b2p66header2.Text = addressnum + soy + road + aumper + province + post;
            b2p66header3.Text = phone;
            b2p67header1.Text = schooldata.sCompany;
            b2p67header2.Text = addressnum + soy + road + aumper + province + post;
            b2p67header3.Text = phone;
            b2p68header1.Text = schooldata.sCompany;
            b2p68header2.Text = addressnum + soy + road + aumper + province + post;
            b2p68header3.Text = phone;
            b2p69header1.Text = schooldata.sCompany;
            b2p69header2.Text = addressnum + soy + road + aumper + province + post;
            b2p69header3.Text = phone;
            b2p70header1.Text = schooldata.sCompany;
            b2p70header2.Text = addressnum + soy + road + aumper + province + post;
            b2p70header3.Text = phone;
            b2p71header1.Text = schooldata.sCompany;
            b2p71header2.Text = addressnum + soy + road + aumper + province + post;
            b2p71header3.Text = phone;
            b2p72header1.Text = schooldata.sCompany;
            b2p72header2.Text = addressnum + soy + road + aumper + province + post;
            b2p72header3.Text = phone;
            b2p73header1.Text = schooldata.sCompany;
            b2p73header2.Text = addressnum + soy + road + aumper + province + post;
            b2p73header3.Text = phone;
            b2p74header1.Text = schooldata.sCompany;
            b2p74header2.Text = addressnum + soy + road + aumper + province + post;
            b2p74header3.Text = phone;
            b2p75header1.Text = schooldata.sCompany;
            b2p75header2.Text = addressnum + soy + road + aumper + province + post;
            b2p75header3.Text = phone;
            b2p76header1.Text = schooldata.sCompany;
            b2p76header2.Text = addressnum + soy + road + aumper + province + post;
            b2p76header3.Text = phone;
            b2p77header1.Text = schooldata.sCompany;
            b2p77header2.Text = addressnum + soy + road + aumper + province + post;
            b2p77header3.Text = phone;
            b2p78header1.Text = schooldata.sCompany;
            b2p78header2.Text = addressnum + soy + road + aumper + province + post;
            b2p78header3.Text = phone;
            b2p79header1.Text = schooldata.sCompany;
            b2p79header2.Text = addressnum + soy + road + aumper + province + post;
            b2p79header3.Text = phone;
            b2p80header1.Text = schooldata.sCompany;
            b2p80header2.Text = addressnum + soy + road + aumper + province + post;
            b2p80header3.Text = phone;
            b2p81header1.Text = schooldata.sCompany;
            b2p81header2.Text = addressnum + soy + road + aumper + province + post;
            b2p81header3.Text = phone;
            b2p82header1.Text = schooldata.sCompany;
            b2p82header2.Text = addressnum + soy + road + aumper + province + post;
            b2p82header3.Text = phone;
            b2p83header1.Text = schooldata.sCompany;
            b2p83header2.Text = addressnum + soy + road + aumper + province + post;
            b2p83header3.Text = phone;
            b2p84header1.Text = schooldata.sCompany;
            b2p84header2.Text = addressnum + soy + road + aumper + province + post;
            b2p84header3.Text = phone;
            b2p85header1.Text = schooldata.sCompany;
            b2p85header2.Text = addressnum + soy + road + aumper + province + post;
            b2p85header3.Text = phone;
            b2p86header1.Text = schooldata.sCompany;
            b2p86header2.Text = addressnum + soy + road + aumper + province + post;
            b2p86header3.Text = phone;
            b2p87header1.Text = schooldata.sCompany;
            b2p87header2.Text = addressnum + soy + road + aumper + province + post;
            b2p87header3.Text = phone;
            b2p88header1.Text = schooldata.sCompany;
            b2p88header2.Text = addressnum + soy + road + aumper + province + post;
            b2p88header3.Text = phone;
            b2p89header1.Text = schooldata.sCompany;
            b2p89header2.Text = addressnum + soy + road + aumper + province + post;
            b2p89header3.Text = phone;
            b2p90header1.Text = schooldata.sCompany;
            b2p90header2.Text = addressnum + soy + road + aumper + province + post;
            b2p90header3.Text = phone;

            year1.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year2.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year3.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year4.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year5.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year6.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year7.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year8.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year9.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year10.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year11.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year12.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year13.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year14.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year15.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year16.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year17.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year18.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year19.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year20.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year21.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year22.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year23.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year24.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year25.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year26.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year27.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year28.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year29.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year30.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year31.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year32.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year33.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year34.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year35.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year36.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year37.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year38.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year39.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year40.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year41.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year42.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year43.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year44.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year45.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            paper5.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            paper5t2.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            paper5t3.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
             
            year47.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year48.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year49.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year50.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year51.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year52.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year53.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year54.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year55.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year56.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year57.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year58.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year59.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year60.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year61.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year62.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year63.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year64.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year65.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year66.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year67.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year68.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year69.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year70.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year71.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year72.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year73.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year74.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year75.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year76.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year77.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year78.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year79.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year80.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year81.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year82.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year83.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year84.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year85.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year86.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year87.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year88.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year89.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year90.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            year91.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            paper5Ex.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            paper5t2ex.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            paper5t3ex.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];

            t2year1.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year2.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year3.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year4.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year5.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year6.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year7.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year8.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year9.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year10.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year11.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year12.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year13.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year14.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year15.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year16.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year17.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year18.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year19.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year20.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year21.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year22.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year23.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year24.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year25.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year26.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year27.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year28.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year29.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year30.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year31.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year32.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year33.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year34.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year35.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year36.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year37.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year38.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year39.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year40.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year41.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year42.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year43.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year44.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year45.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];

            t2year46.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year47.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year48.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year49.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year50.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year51.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year52.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year53.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year54.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year55.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year56.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year57.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year58.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year59.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year60.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year61.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year62.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year63.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year64.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year65.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year66.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year67.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year68.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year69.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year70.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year71.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year72.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year73.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year74.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year75.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year76.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year77.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year78.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year79.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year80.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year81.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year82.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year83.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year84.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year85.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year86.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year87.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year88.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year89.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];
            t2year90.Text = "รายงานผลการประเมินการพัฒนาผู้เรียน ประจำปีการศึกษา " + Request.QueryString["term"] + "/" + Request.QueryString["year"];

            if (schooldata != null)
            {
                schoolpicture.Src = schooldata.sImage;
                Img1.Src = schooldata.sImage;
                Img2.Src = schooldata.sImage;
                Img3.Src = schooldata.sImage;
                Img4.Src = schooldata.sImage;
                Img5.Src = schooldata.sImage;
                Img6.Src = schooldata.sImage;
                Img7.Src = schooldata.sImage;
                Img8.Src = schooldata.sImage;
                Img9.Src = schooldata.sImage;
                Img10.Src = schooldata.sImage;
                Img11.Src = schooldata.sImage;
                Img12.Src = schooldata.sImage;
                Img13.Src = schooldata.sImage;
                Img14.Src = schooldata.sImage;
                Img15.Src = schooldata.sImage;
                Img16.Src = schooldata.sImage;
                Img17.Src = schooldata.sImage;
                Img18.Src = schooldata.sImage;
                Img19.Src = schooldata.sImage;
                Img20.Src = schooldata.sImage;
                Img21.Src = schooldata.sImage;
                Img22.Src = schooldata.sImage;
                Img23.Src = schooldata.sImage;
                Img24.Src = schooldata.sImage;
                Img25.Src = schooldata.sImage;
                Img26.Src = schooldata.sImage;
                Img27.Src = schooldata.sImage;
                Img28.Src = schooldata.sImage;
                Img29.Src = schooldata.sImage;
                Img30.Src = schooldata.sImage;
                Img31.Src = schooldata.sImage;
                Img32.Src = schooldata.sImage;
                Img33.Src = schooldata.sImage;
                Img34.Src = schooldata.sImage;
                Img35.Src = schooldata.sImage;
                Img36.Src = schooldata.sImage;
                Img37.Src = schooldata.sImage;
                Img38.Src = schooldata.sImage;
                Img39.Src = schooldata.sImage;
                Img40.Src = schooldata.sImage;
                Img41.Src = schooldata.sImage;
                Img42.Src = schooldata.sImage;
                Img43.Src = schooldata.sImage;
                Img44.Src = schooldata.sImage;
                Img45.Src = schooldata.sImage;
                Img46.Src = schooldata.sImage;
                Img47.Src = schooldata.sImage;
                Img48.Src = schooldata.sImage;
                Img49.Src = schooldata.sImage;
                Img50.Src = schooldata.sImage;
                Img51.Src = schooldata.sImage;
                Img52.Src = schooldata.sImage;
                Img53.Src = schooldata.sImage;
                Img54.Src = schooldata.sImage;
                Img55.Src = schooldata.sImage;
                Img56.Src = schooldata.sImage;                
                Img58.Src = schooldata.sImage;
                Img59.Src = schooldata.sImage;
                Img60.Src = schooldata.sImage;
                Img61.Src = schooldata.sImage;
                Img62.Src = schooldata.sImage;
                Img63.Src = schooldata.sImage;
                Img64.Src = schooldata.sImage;
                Img65.Src = schooldata.sImage;
                Img66.Src = schooldata.sImage;
                Img67.Src = schooldata.sImage;
                Img68.Src = schooldata.sImage;
                Img69.Src = schooldata.sImage;
                Img70.Src = schooldata.sImage;
                Img71.Src = schooldata.sImage;
                Img72.Src = schooldata.sImage;
                Img73.Src = schooldata.sImage;
                Img74.Src = schooldata.sImage;
                Img75.Src = schooldata.sImage;
                Img76.Src = schooldata.sImage;
                Img77.Src = schooldata.sImage;
                Img78.Src = schooldata.sImage;
                Img79.Src = schooldata.sImage;
                Img80.Src = schooldata.sImage;
                Img81.Src = schooldata.sImage;                
                Img83.Src = schooldata.sImage;
                Img84.Src = schooldata.sImage;
                Img85.Src = schooldata.sImage;
                Img86.Src = schooldata.sImage;
                Img87.Src = schooldata.sImage;
                Img88.Src = schooldata.sImage;
                Img89.Src = schooldata.sImage;
                Img90.Src = schooldata.sImage;
                Img91.Src = schooldata.sImage;

                Img92.Src = schooldata.sImage;
                Img93.Src = schooldata.sImage;
                Img94.Src = schooldata.sImage;
                Img95.Src = schooldata.sImage;
                Img96.Src = schooldata.sImage;
                Img97.Src = schooldata.sImage;
                Img98.Src = schooldata.sImage;
                Img99.Src = schooldata.sImage;
                Img100.Src = schooldata.sImage;
                Img101.Src = schooldata.sImage;
                Img102.Src = schooldata.sImage;
                Img103.Src = schooldata.sImage;
                Img104.Src = schooldata.sImage;
                Img105.Src = schooldata.sImage;
                Img106.Src = schooldata.sImage;
                Img107.Src = schooldata.sImage;
                Img108.Src = schooldata.sImage;
                Img109.Src = schooldata.sImage;
                Img110.Src = schooldata.sImage;
                Img111.Src = schooldata.sImage;
                Img112.Src = schooldata.sImage;
                Img113.Src = schooldata.sImage;
                Img114.Src = schooldata.sImage;
                Img115.Src = schooldata.sImage;
                Img116.Src = schooldata.sImage;
                Img117.Src = schooldata.sImage;
                Img118.Src = schooldata.sImage;
                Img119.Src = schooldata.sImage;
                Img120.Src = schooldata.sImage;
                Img121.Src = schooldata.sImage;
                Img122.Src = schooldata.sImage;
                Img123.Src = schooldata.sImage;
                Img124.Src = schooldata.sImage;
                Img125.Src = schooldata.sImage;
                Img126.Src = schooldata.sImage;
                Img127.Src = schooldata.sImage;
                Img128.Src = schooldata.sImage;
                Img129.Src = schooldata.sImage;
                Img130.Src = schooldata.sImage;
                Img131.Src = schooldata.sImage;
                Img132.Src = schooldata.sImage;
                Img133.Src = schooldata.sImage;
                Img134.Src = schooldata.sImage;
                Img135.Src = schooldata.sImage;
                Img136.Src = schooldata.sImage;
                Img137.Src = schooldata.sImage;
                Img138.Src = schooldata.sImage;
                Img139.Src = schooldata.sImage;
                Img140.Src = schooldata.sImage;
                Img141.Src = schooldata.sImage;
                Img142.Src = schooldata.sImage;
                Img143.Src = schooldata.sImage;
                Img144.Src = schooldata.sImage;
                Img145.Src = schooldata.sImage;
                Img146.Src = schooldata.sImage;
                Img147.Src = schooldata.sImage;
                Img148.Src = schooldata.sImage;
                Img149.Src = schooldata.sImage;
                Img150.Src = schooldata.sImage;
                Img151.Src = schooldata.sImage;
                Img152.Src = schooldata.sImage;
                Img153.Src = schooldata.sImage;
                Img154.Src = schooldata.sImage;
                Img155.Src = schooldata.sImage;
                Img156.Src = schooldata.sImage;
                Img157.Src = schooldata.sImage;
                Img158.Src = schooldata.sImage;
                Img159.Src = schooldata.sImage;
                Img160.Src = schooldata.sImage;
                Img161.Src = schooldata.sImage;
                Img162.Src = schooldata.sImage;
                Img163.Src = schooldata.sImage;
                Img164.Src = schooldata.sImage;
                Img165.Src = schooldata.sImage;
                Img166.Src = schooldata.sImage;
                Img167.Src = schooldata.sImage;
                Img168.Src = schooldata.sImage;
                Img169.Src = schooldata.sImage;
                Img170.Src = schooldata.sImage;
                Img171.Src = schooldata.sImage;
                Img172.Src = schooldata.sImage;
                Img173.Src = schooldata.sImage;
                Img174.Src = schooldata.sImage;
                Img175.Src = schooldata.sImage;
                Img176.Src = schooldata.sImage;
                Img177.Src = schooldata.sImage;
                Img178.Src = schooldata.sImage;
                Img179.Src = schooldata.sImage;
                Img170.Src = schooldata.sImage;
            }
            
            class1.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class2.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class3.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class4.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class5.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class6.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class7.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class8.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class9.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class10.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class11.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class12.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class13.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class14.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class15.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class16.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class17.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class18.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class19.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class20.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class21.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class22.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class23.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class24.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class25.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class26.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class27.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class28.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class29.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class30.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class31.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class32.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class33.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class34.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class35.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class36.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class37.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class38.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class39.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class40.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class41.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class42.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class43.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class44.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class45.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class46.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;

            t2class1.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class2.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class3.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class4.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class5.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class6.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class7.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class8.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class9.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class10.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class11.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class12.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class13.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class14.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class15.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class16.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class17.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class18.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class19.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class20.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class21.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class22.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class23.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class24.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class25.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class26.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class27.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class28.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class29.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class30.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class31.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class32.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class33.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class34.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class35.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class36.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class37.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class38.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class39.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class40.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class41.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class42.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class43.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class44.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class45.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class46.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class47.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;

            class47.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class48.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class49.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class50.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class51.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class52.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class53.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class54.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class55.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class56.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class57.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class58.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class59.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class60.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class61.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class62.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class63.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class64.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class65.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class66.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class67.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class68.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class69.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class70.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class71.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class72.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class73.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class74.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class75.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class76.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class77.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class78.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class79.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class80.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class81.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class82.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class83.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class84.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class85.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class86.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class87.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class88.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class89.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class90.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class91.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            class92.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;

            t2class48.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class49.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class50.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class51.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class52.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class53.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class54.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class55.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class56.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class57.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class58.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class59.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class60.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class61.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class62.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class63.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class64.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class65.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class66.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class67.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class68.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class69.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class70.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class71.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class72.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class73.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class74.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class75.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class76.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class77.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class78.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class79.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class80.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class81.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class82.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class83.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class84.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class85.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class86.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class87.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class88.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class89.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class90.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class91.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class92.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class93.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;
            t2class94.Text = "ชั้นปี " + room.SubLevel + " / " + room2.nTSubLevel2;

            string year = Request.QueryString["year"];
            string userterm = Request.QueryString["term"];
            string userterm2 = "";
            if (userterm == "1") userterm2 = "2";
            if (userterm == "2") userterm2 = "1";

            var roomz = _db.TSubLevels.Where(w => w.nTSubLevel == idlvn && w.SchoolID == userData.CompanyID).FirstOrDefault();
            var room2z = _db.TTermSubLevel2.Where(w => w.nTermSubLevel2 == idlv2n && w.SchoolID == userData.CompanyID).FirstOrDefault();
           
            if (!IsPostBack)
            {
                OpenData();


            }
        }







        private void OpenData()
        {
            JabJaiSchoolGradeEntities _dbGrade = new JabJaiSchoolGradeEntities(Connection.StringConnectionSchoolGrade());
            JabJaiEntities _db = new JabJaiEntities(Connection.StringConnectionSchool(HttpContext.Current.Session["sEntities"].ToString()));
            JabJaiMasterEntities dbmaster = Connection.MasterEntities();

            string sEntities = Session["sEntities"].ToString();
            var tCompany = dbmaster.TCompanies.Where(w => w.sEntities == sEntities).FirstOrDefault();

            string year = Request.QueryString["year"];
            string userterm = Request.QueryString["term"];
            string userterm2 = "";
            if (userterm == "1") userterm2 = "2";
            else if (userterm == "2") userterm2 = "1";
            string idlv2 = Request.QueryString["idlv2"];
            string idlv = Request.QueryString["idlv"];
            int? idlvn = Int32.Parse(idlv);

            int? useryear = Int32.Parse(year);
            int? idlv2n = Int32.Parse(idlv2);
            string username = "";
            int? ntermsublv2 = 0;
            int nyear = 0;
            string nterm = "";
            string nterm2 = "";
            int ntermtable = 0;

            var room = _db.TSubLevels.Where(w => w.nTSubLevel == idlvn).FirstOrDefault();
            var room2 = _db.TTermSubLevel2.Where(w => w.nTermSubLevel2 == idlv2n).FirstOrDefault();



            //txtpaper4.Text = "บันทึกเวลาเรียน";

            foreach (var ff in _db.TYears.Where(w => w.numberYear == useryear && w.SchoolID == userData.CompanyID))
            {
                nyear = ff.nYear;
            }

            foreach (var ee in _db.TTerms.Where(w => w.sTerm == userterm && w.nYear == nyear && w.SchoolID == userData.CompanyID && w.cDel == null))
            {
                nterm = ee.nTerm;
            }

            foreach (var ee in _db.TTerms.Where(w => w.sTerm == userterm2 && w.nYear == nyear && w.cDel == null))
            {
                nterm2 = ee.nTerm;
            }

            
            
            int number2 = 0;
            int count = 0;
            int gradeid = 0;
            foreach (var b in _dbGrade.TGrades.Where(w => w.nTerm == nterm && w.nTermSubLevel2 == idlv2n && w.SchoolID == userData.CompanyID))
            {
                gradeid = b.nGradeId;
                if (number2 == 0) { count = count + 1; }
                if (number2 == 1) { count = count + 1; }
                if (number2 == 2) { count = count + 1; }
                if (number2 == 3) { count = count + 1; }
                if (number2 == 4) { count = count + 1; }
                if (number2 == 5) { count = count + 1; }
                if (number2 == 6) { count = count + 1; }
                if (number2 == 7) { count = count + 1; }
                if (number2 == 8) { count = count + 1; }
                if (number2 == 9) { count = count + 1; }
                if (number2 == 10) { count = count + 1; }
                if (number2 == 11) { count = count + 1; }
                if (number2 == 12) { count = count + 1; }
                if (number2 == 13) { count = count + 1; }
                if (number2 == 14) { count = count + 1; }
                if (number2 == 15) { count = count + 1; }
                if (number2 == 16) { count = count + 1; }
                if (number2 == 17) { count = count + 1; }
                if (number2 == 18) { count = count + 1; }
                if (number2 == 19) { count = count + 1; }
                if (number2 == 20) { count = count + 1; }
                if (number2 == 21) { count = count + 1; }
                if (number2 == 22) { count = count + 1; }
                if (number2 == 23) { count = count + 1; }
                if (number2 == 24) { count = count + 1; }
                if (number2 == 25) { count = count + 1; }
                number2 = number2 + 1;
            }



           

            maxstudy.Text = count.ToString();

            int totalstudent = 0;

            foreach (var aa in _dbGrade.TGradeDetails.Where(w => w.SchoolID == userData.CompanyID && w.nGradeId == gradeid))
            {
                totalstudent = totalstudent + 1;
            }

            int totalpage = (totalstudent / 45) + 1;
            int fromstudent = (totalpage * 45) - 44;

            pageheader.Text = totalstudent.ToString();
        }

    }

}