//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.PaymentGateway_KBank_Checkout {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class aspx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal aspx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PaymentGateway_KBank_Checkout.aspx", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to main.
        /// </summary>
        internal static string Button_BackToMain {
            get {
                return ResourceManager.GetString("Button-BackToMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Button_Confirm {
            get {
                return ResourceManager.GetString("Button-Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask for more information.
        /// </summary>
        internal static string Contact01 {
            get {
                return ResourceManager.GetString("Contact01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact: 02-096-2550 ext. 1.
        /// </summary>
        internal static string Contact02 {
            get {
                return ResourceManager.GetString("Contact02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Form_Amount {
            get {
                return ResourceManager.GetString("Form-Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baht.
        /// </summary>
        internal static string Form_BahtUnit {
            get {
                return ResourceManager.GetString("Form-BahtUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string Form_Class {
            get {
                return ResourceManager.GetString("Form-Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee.
        /// </summary>
        internal static string Form_Fee {
            get {
                return ResourceManager.GetString("Form-Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order number.
        /// </summary>
        internal static string Form_OrderNumber {
            get {
                return ResourceManager.GetString("Form-OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top-up details.
        /// </summary>
        internal static string Form_Title {
            get {
                return ResourceManager.GetString("Form-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top-up.
        /// </summary>
        internal static string Form_Topic {
            get {
                return ResourceManager.GetString("Form-Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Form_Total {
            get {
                return ResourceManager.GetString("Form-Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system has not been activated..
        /// </summary>
        internal static string System_Message01 {
            get {
                return ResourceManager.GetString("System-Message01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The top-up system was temporarily interrupted..
        /// </summary>
        internal static string System_Message02 {
            get {
                return ResourceManager.GetString("System-Message02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system is down. The top up service is temporarily closed. The team is working to fix it as soon as possible.
        ///Don&apos;t be alarmed, students can spend at school in the offline system as usual.&lt;br&gt;
        ///Thank you.
        /// </summary>
        internal static string System_Message03 {
            get {
                return ResourceManager.GetString("System-Message03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification of temporary closure of the online payment system from 11:00 p.m. - 1:00 a.m. every day.&lt;br /&gt;
        ///                            &lt;br /&gt;
        ///                            sorry for the inconvenience.
        /// </summary>
        internal static string System_Message04 {
            get {
                return ResourceManager.GetString("System-Message04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระบบชำระเงินออนไลน์ไม่สามารถใช้งานได้ชั่วคราวเนื่องจากมีปัญหากับ PromptPay หรือระบบภายใน ทางเราจะทำการแก้ไขปัญหาและเปิดระบบให้บริการเร็วที่สุดที่เป็นไปได้ ขอบคุณที่รอคอยและขออภัยในความไม่สะดวกที่เกิดขึ้น
        ///&lt;br&gt;&lt;br&gt;
        ///
        ///The online payment system is temporarily unavailable due to issues with PromptPay or internal issue. We will restore the system as soon as the problem is resolved..
        /// </summary>
        internal static string System_Message05 {
            get {
                return ResourceManager.GetString("System-Message05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful transaction.
        /// </summary>
        internal static string System_ProcessComplete {
            get {
                return ResourceManager.GetString("System-ProcessComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to complete the transaction..
        /// </summary>
        internal static string System_ProcessFail {
            get {
                return ResourceManager.GetString("System-ProcessFail", resourceCulture);
            }
        }
    }
}
