//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.PaymentGateway_UnderMaintenance {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class aspx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal aspx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PaymentGateway_UnderMaintenance.aspx", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to main.
        /// </summary>
        internal static string Button_BackToMain {
            get {
                return ResourceManager.GetString("Button-BackToMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask for more information.
        /// </summary>
        internal static string Contact01 {
            get {
                return ResourceManager.GetString("Contact01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact: 02-096-2550 ext. 1.
        /// </summary>
        internal static string Contact02 {
            get {
                return ResourceManager.GetString("Contact02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span style=&quot;font-size: 26px;&quot;&gt;Notification of temporary shutdown of online tuition payment system.&lt;/span&gt;&lt;br&gt;
        ///&lt;span style=&quot;font-size: 22px;&quot;&gt;Friday, October 20, 2023 to Monday, October 23, 2023.&lt;/span&gt;&lt;br&gt;
        ///&lt;br&gt;
        ///&lt;span style=&quot;font-size: 26px;&quot;&gt;We apologizes for the inconvenience.&lt;/span&gt;.
        /// </summary>
        internal static string System_Message01 {
            get {
                return ResourceManager.GetString("System-Message01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The online payment system is temporarily unavailable due to issues with PromptPay or internal issue. We will restore the system as soon as the problem is resolved..
        /// </summary>
        internal static string System_Message02 {
            get {
                return ResourceManager.GetString("System-Message02", resourceCulture);
            }
        }
    }
}
