<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="CallbackResponse.aspx.cs" Inherits="FingerprintPayment.PaymentGateway.KBank.KBankPromptPay.CallbackResponse" %>

<!DOCTYPE html>
<html>
<head>
    <title>SignalR Simple Chat</title>
    <style type="text/css">
        .container {
            background-color: #99CCFF;
            border: thick solid #808080;
            padding: 20px;
            margin: 20px;
        }
    </style>
</head>
<body>
    <input type="text" id="imei" name="imei" /><br />
    <textarea id="callbackData" name="callbackData" rows="10" cols="100"></textarea>
    <br />
    <button type="button" id="btnCallbackResponse">CallbackResponse</button>
    <button type="button" id="btnDisplayMapping">DisplayMapping</button>
    <button type="button" id="btnSendMessageToClient">SendMessageToClient</button>

    <!--Script references. -->
    <!--Reference the jQuery library. -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" type="text/javascript"></script>
    <!--Reference the SignalR library. -->
    <script src="https://ajax.aspnetcdn.com/ajax/signalr/jquery.signalr-2.2.2.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src='https://signalrpos.schoolbright.co/signalr/hubs'></script>
    <!--Add script to update the page and send messages.-->
    <script type="text/javascript">
        $(function () {

            $.connection.hub.url = "https://signalrpos.schoolbright.co/signalr/hubs";

            // Declare a proxy to reference the hub. 
            var kbank = $.connection.kBankHub;

            // Create a function that the hub can call to broadcast messages.
            kbank.client.callbackResponseDebug = function (res) {
                console.log('callbackResponseDebug');
                console.log(res);
            };

            kbank.client.callbackResponse = function (res) {
                console.log('callbackResponse');
                console.log(res);
            };

            // Start the connection.
            $.connection.hub.start().done(function () {
                kbank.server.iMEIMapping('<%= Request.QueryString["imei"].ToString() %>');
            });

            $.connection.hub.error(function (e) {
                console.log(e);
            });

            $("#btnCallbackResponse").bind({
                click: function () {
                    $.ajax({
                        type: "POST",
                        url: "CallbackResponse.aspx/TestCallbackResponse",
                        data: JSON.stringify({ imei: $('#imei').val(), callbackData: $('#callbackData').val() }),
                        contentType: "application/json; charset=utf-8",
                        dataType: "json",
                        success: function (result) {
                            //console.log(result.d);
                            var r = JSON.parse(result.d);
                            console.log(r);
                        },
                        beforeSend: function () {
                            // Display upload-progress
                        },
                        error: function (response) {
                            alert(response.responseText);
                        }
                    });

                    return false;
                }
            });

            $("#btnDisplayMapping").bind({
                click: function () {

                    kbank.server.displayMapping();

                    return false;
                }
            });

            $("#btnSendMessageToClient").bind({
                click: function () {

                    kbank.server.sendMessageToClient('test');

                    return false;
                }
            });

        });
    </script>
</body>
</html>
